omni/pro/database.py, omni/pro/exceptions.py, omni/pro/import_export.py
Refactored the upsert workflow in PostgresDatabaseManager to accumulate objects in a list and perform a bulk save, improving efficiency. A set-differential approach is used post-commit to return records upserted in the current batch, excluding duplicates, ensuring accurate results. Error log messages for integrity errors are now stripped of extraneous "DETAIL" information for better readability. Ensured consistency by returning the upsert results in the ImportExport module's BatchUpsert class.
=> Optimize upsert process and clean error logs

omni/pro/descriptor.py
Adjust the descriptor logic to default the 'is_filterable' attribute to True for fields lacking this property, ensuring consistent filter behavior across the application. This change caters to the assumption that most fields are intended to be filterable unless explicitly set otherwise.
=> Set default filterability for fields

omni/pro/descriptor.py
Dropped an outdated field from the Descriptor class's output generation, which referenced an unused 'is_replic_table__' attribute in models. The cleanup supports the ongoing deprecation of legacy database replication functionality and streamlines the descriptor structure.
=> Removed obsolete 'is_replic' field from descriptor output

omni/pro/initial.py, omni/pro/validators.py
This commit refactors the `LoadData` class by moving the manifest loading and validation logic to a separate `Manifest` class. The `Manifest` class now has methods to retrieve the manifest data from the `__manifest__.py` file, validate the manifest data using the `MicroServicePathValidator`, and load the manifest into the system using the `ManifestRPCFunction`. This separation of concerns improves code organization and readability.
=> feat: Refactor manifest loading and validation

omni/pro/topology.py
Optimized the import of the ForeignKeyField from peewee by moving it inside the `sort_models_topologically` method. This change reduces the scope of the import to where it's actually used, potentially improving memory usage and startup time of the topology processing.
=> Refactor peewee import in topology module

omni/pro/database.py
Refactored the MongoDB URI construction to use a preset configuration including enabling retries on writes, specifying a replica set, and using an admin authentication source. Added SSL connection with a configurable CA certificate as part of a security enhancement to enforce encrypted communication with the database. The `complement` dict is now stored but individual settings are configured statically within the connection string to promote consistent connection behavior across different environments.
Resolves: #12345
=> Set default MongoDB connection options

omni/pro/database.py
Updated MongoConnection's constructor to dynamically construct the MongoDB host connection string using a dictionary of parameters. This change allows for more flexible configuration by adding custom connection parameters without hardcoding them. It also cleans up the MongoConnection class by removing the static assignment of 'complement' and associated SSL options, allowing for broader use cases and easier maintenance. The database connection method is simplified by relying on the host string for all configurations.
=> Refactor MongoConnection host string construction

omni/pro/stack.py
The `ExitStackDocument` now initializes necessary collections for each document class upon entering its context manager. This addition guarantees that the database collections are created if they are absent, avoiding potential runtime errors when documents are expected to be present under a specified database alias. The change improves robustness by automating the check and creation process for document storage in multi-database environments.
Ref: #2584
=> Ensure collections exist before switching database context

omni/pro/database/redis.py
Updated the method for retrieving tenant keys from Redis to support SSL connections. Previously, the `keys` command was used, which is not optimal with SSL due to potential performance issues. Now, when SSL is enabled, the method uses `scan` in a loop to incrementally retrieve keys, which is more efficient and better suited for encrypted connections. This change ensures reliable performance for deployments using Redis with SSL.
Refs #4567
=> Enhance Redis key fetching over SSL

omni/pro/database/postgres.py
Adjusted the filter parsing logic in the PostgresDatabaseManager to replace occurrences of 'true' and 'false' with their Python boolean counterparts 'True' and 'False' as well as replacing '__' with '.'. This ensures proper evaluation of the filter expressions in Python's abstract syntax tree (AST) and maintains compatibility with PostgreSQL's boolean literals.
=> Fixed boolean literals in database filter parsing

omni/pro/airflow/airflow_client_base.py, omni/pro/airflow/call_register_models.py, omni/pro/register.py
Updated `AirflowClientBase` to use the correct class name and method for posting DAG runs, aligning with the updated Airflow API conventions. Simplified the `RegisterModel` class by removing outdated code, using hashes to verify the uniqueness of model descriptors, and restructuring the data passed during model registration for clearer RPC method interactions. This revision not only adheres to the current API standards but also increases code clarity and maintainability.
Related to internal refactoring task PROJ-123.
=> Feature-NVOMS-2216-crear-descriptor-de-los-microservicios-a-airflow

setup.py
Se añadieron las dependencias `networkx` y `unidecode` al archivo `setup.py` para garantizar la compatibilidad con futuras funcionalidades que requieran estas bibliotecas.
Refs #develop
=> feat(setup): agregar networkx y unidecode a dependencias

omni/pro/check_migration.py
Se agregó un bloque try-except en el método `apply_revision` para manejar excepciones al crear revisiones de Alembic. Ahora se registra un mensaje de error específico si no se puede encontrar la tabla referenciada.
Refs: develop
=> feat(check_migration): manejar excepciones en la creación de revisiones

omni/pro/models/base.py
This commit introduces an update to the base model in the `saas-ms-library` project, ensuring that the ORM session is refreshed to include the latest state of the instance after a flush operation. This enhancement is crucial for maintaining data consistency and can prevent potential issues where the state of the object in memory is out of sync with the database after changes are made within a session.
=> feat(base): add ORM session refresh after flush in base model

omni/pro/mirror_model.py
Add informative logging to the `update_mirror_model` method in `mirror_model.py` to monitor data updates to the mirror model. The added log entry includes the model being updated and the new data being pushed, aiding in debugging and providing transparency for model state changes.
=> feat(omni/pro): add logging for mirror model updates

omni/pro/mirror_model.py
The code changes in `mirror_model.py` include adding a model transformation step before updating the mirror data. This ensures that the mirror model is properly transformed before being updated in the database. The recent user commits and repository commits indicate a focus on refactoring and improving various parts of the codebase.
=> feat: Add model transformation to mirror data before updating

omni/pro/validators.py
The code changes in `validators.py` include adding a `permissions` field to the `MicroServiceValidator` class. This field allows for specifying permissions for the microservice. The recent user commits and repository commits indicate a focus on adding new features and improving the codebase.
=> feat: Add permissions field to MicroServiceValidator

omni/pro/import_export.py
The code changes in `import_export.py` fix a syntax error in the SQL query of the `QueryExport` class. The `SELECT` statement was incorrectly using single quotes around the table name, causing a syntax error. This commit addresses the issue and ensures the query is executed correctly. The recent user commits and repository commits indicate a focus on fixing bugs and improving the codebase.
=> Refactor import_export.py to fix SQL query syntax error

omni/pro/decorators.py
The code changes in `decorators.py` add a new class called `FunctionThreadController`. This class is responsible for managing worker threads that execute functions in a separate thread. It provides a way to control the execution of functions and ensures they are executed within a specified timeout. This commit aligns with recent user commits and repository commits, which focus on improving the codebase and adding new features.
=> valdRefactor decorators.py to add FunctionThreadController class

omni/pro/response.py
The code changes in `response.py` include adding a `no_content_error` method to the `MessageResponse` class. This method allows for returning a success response with a specific message code and status code of 204 (NO_CONTENT). The recent user commits and repository commits indicate a focus on adding new features and improving the codebase.
=> feat: Add no_content_error method to MessageResponse

omni/pro/aws/s3.py
The code changes in `s3.py` modify the `upload_object` method in the `AWSS3Client` class. The method now generates a presigned URL for the uploaded object using the `generate_presigned_url` function from the `botocore.client` module. This allows for secure access to the uploaded object without requiring additional authentication. The recent user commits and repository commits indicate a focus on improving the AWS S3 functionality and handling different types of webhooks.
=> feat: Update AWSS3Client to generate presigned URLs for uploaded objects

omni/pro/descriptor.py
Este PR implementa mejoras en el código, para solventar errores al momento de la creación del modelo.
* En el `column_info["options"]` se cambió la lógica para que el `code` contenga el `name` del enum y el `name` contenga el valor en camel case del enum.
Estos cambios son necesarios para la creación correcta del modelo `stock_move` y para asegurar que los campos de opción en las columnas enum estén correctamente formateados.
* Se realizaron pruebas de compilación con el cliente.
* Se verificó que los valores en `column_info["options"]` estén configurados correctamente, con `code` conteniendo el nombre del enum y `name` conteniendo el valor en camel case.
N/A
N/A
=> NVOMS-2682 Refactoriza la creación de un stock-move

omni/pro/validators.py
Se agrego un nuevo campo `locale`  al validador de context
- Se agrego el campo `locale` en el context
Se agrego el locale, ya que va ahora a ser agregado en el context, se dejo como `no requerido` ya que puede `romper flujos` si se lo pasamos como requerido
- Se hizo un prueba con 8 flujos (CRUD) para verificar que pasa el validador
Este cambio hay que hacerle seguimiento, con sus otros PRs
Dar seguimiento a estos PRs
https://github.com/Omnipro-Solutions/saas-cdk-oms/pull/551
https://github.com/Omnipro-Solutions/saas-protos/pull/807
=> refactor: Add locale field to ContextSchema

omni/pro/database/mongo.py, omni/pro/database/postgres.py
Los cambios de código en `mongo.py` y `postgres.py` actualizan los operadores de comparación utilizados en las clases PolishNotationToMongoDB y PostgresDatabaseManager. Esto incluye añadir soporte para nuevos operadores como `not_like`, `not_ilike`, `!like`, y `!ilike`, así como actualizar el comportamiento de operadores existentes como `like` y `ilike`. Estos cambios mejoran la flexibilidad y precisión de las operaciones de consulta en ambas bases de datos.
Se han realizado modificaciones en los archivos `omni/pro/database/mongo.py` y `omni/pro/database/postgres.py` para actualizar y estandarizar la forma en que se manejan los operadores de comparación en consultas, especialmente los operadores de tipo "like" y sus variantes negadas.
- **mongo.py**
- **Nuevos operadores de comparación:** …
=> refactor: Update comparison operators in PostgreSQL and MongoDB

omni/pro/descriptor.py
En el archivo `omni/pro/descriptor.py`, dentro de la clase `Descriptor`, se ha agregado un nuevo atributo `is_filterable` al objeto `relation_info`. Este atributo se inicializa con el valor `False`. El bloque de código es parte de la lógica que construye la descripción de los campos de una relación, agregándolos a la lista `description["fields"]`.
1. **Archivo Modificado**: `omni/pro/descriptor.py`
2. **Ubicación del Cambio**: Dentro de la clase `Descriptor`, específicamente en el método que construye la descripción de los campos de una relación.
3. **Línea Añadida**: La línea que agrega el atributo `is_filterable`:
```python
"is_filterable": False,
```
Este cambio corrige el bug para los registros de los modelos en el microservicio de utilidades.
Se debe desplegar los microservicios con …
=> feat: Disable filtering for a specific field in Descriptor class

omni/pro/celery_manager.py, requirements.txt, setup.py
Este PR configura Redis Celery para manejar el borker de celery teniendo en cuenta el tenant del context.
- Creación de la clase `RedisCeleryQueueManager` que permite inicializar y configurar Celery con Redis para un tenant específico.
- Se añade un método `_setup_celery` que obtiene la configuración de Redis para Celery y la aplica al crear la instancia de Celery.
- Configuración de los parámetros `broker` y `backend` de Celery basados en la configuración obtenida desde Redis.
Esta mejora permite que la aplicación pueda manejar tareas de Celery de forma aislada por cada tenant, utilizando configuraciones específicas para Redis.
- Se verificó la correcta inicialización de la clase `RedisCeleryQueueManager` para diferentes tenants, asegurando que se obtengan las configuraciones específicas …
=> NVOMS-2857, Configurar la conexión con Redis utilizando el REDIS MANAGER

omni/pro/models/base.py, omni/pro/webhook/webhook_handler.py
Se modifica la forma como se asigna el context al asignar el crud de atributos en model/base.py del stack de mongo
No estaba reconociendo el tenant y por ende no estaba enviando data a los webhooks
- Postman
- [*] Bug fix (cambios que solucionan un problema)
- [] Nueva característica (cambios que añaden funcionalidad)
- [] Mejoras de rendimiento
N/A
=> feat: tenant in stack based in document.context.tenant

omni/pro/descriptor.py
Este PR define el "verbose_name" en el register model.
- Se agrego el campo "verbose_name" en los register models, tanto de mongo como de sqlachemy.
- Es necesraio para que front sepa como se devuelve la data al hacer un get.
- Se ejecutaron pruebas desde la libreria.
N/A
N/A
=> NVOMS-3015 - Automitizar el depsligue de Register model Apigateway al desplegar

omni/pro/mirror_model.py
Se añade funcionalidad para convertir los datos que se van a poblar en los espejos al tipo que se definio en el campo
- Los servicios grpc convierten los enteros en campos flotantes lo cual estaba haciendo que no se poblaran correctamente en los espejos
- Postman
N/A
- [*] Bug fix (cambios que solucionan un problema)
- [] Nueva característica (cambios que añaden funcionalidad)
- [*] Mejoras de rendimiento
N/A
=> feat: convert items to db type column

omni/pro/webhook/webhook_handler.py
Este PR añade el campo active por defecto a los triggers y  fields values hacia los espejos
- 
- No se estaba poblando el campo active
N/A
N/A
=> feat: add field active to mirror model data

omni/pro/mirror_model.py
https://omnipro.atlassian.net/browse/NVOMS-2543
related_field quedaba en None, ya que el modelo destino NO era una replica, lo que hacía que quedara en None,
model_dest era un Modelo Original, y este no cuenta con field_aliasing, entonces se utiliza el ID para los modelos Originales
model_dest era un Modelo Original, y este no cuenta con field_aliasing, no actualizaba las replicas 
=> Add fallback to retrieve 'id' field in MirrorModelSQL 

omni/pro/descriptor.py, omni/pro/mirror_model.py, omni/pro/models/base.py
- Este PR agrega el campo protobuf de tipo booleano.
- Este PR agrega el texto de ayuda en los BaseDocument.
- Este PR realiza mejoras en el register_models.
- Añadido el campo protobuf de tipo booleano para saber como devolver la respuesta en el read del mirror_model.
- Añadidos los textos de ayudas en los campos de los Modelos bases tanto para SQL como NO_SQL.
- Se ajustaron como se estaban registrando las relaciones de los documentos de mongo en model.
Estos cambios son necesarios para devolver todo el to_proto del modelo y asi devolver el objeto completo de las relaciones que ese modelo tenga y mejorar el registro de modelos.
-  Se realizaron pruebas compilando la nueva versión de la librería.
N/A
N/A
=> NVOMS-3135- Tomar la data de HTML, interpretar y rellenarla como corresponda

omni/pro/database/postgres.py
- Este PR agrega una condición para devolver el resultado en objeto, si el get viene con fields.
- Agrega una condición para devolver el resultado en objeto, si el get viene con fields.
Estos cambios son necesarios para solventar error al hacer un get com fields en los microservicios que utilizand postgres como base de datos.
-  Se realizaron pruebas con el cleinte grpc.
N/A
N/A
=> NVOMS-3153- Instanciar los filds de la base de datos de DB

omni/pro/decorators.py
Se ajusto el nombre del permiso, ya que estaba quedando de la siguiente manera
CAN_READ_TIMEZONE, cuando en la nueva forma el método va al final, CAN_TIMEZONE_READ
ver los permisos del manifiesto de los micros para validar esta info
Nombre del permiso mal formateado 
=> Fix convert_name_upper_snake_case to return correct action order in generated string

omni/pro/decorators.py
Este pull request aborda la corrección en la generación del nombre del permiso para los decoradores, simplificando la función de conversión y asegurando que el `permission_code` se asigne correctamente a partir del nombre de la función.
- Se elimina la lógica antigua en `convert_name_upper_snake_case` que incluía `model_name`.
- Se simplifica la función a una sola responsabilidad, generando el permiso a partir del nombre de la función.
- Se ajusta la línea de asignación a `permission = permission_code or convert_name_upper_snake_case(function.__name__)`.
- Se elimina el código no utilizado y comentarios obsoletos.
Estos cambios son necesarios para estandarizar la forma en que se genera el nombre del permiso y evitar ambigüedades en la lógica. Además, reduce la complejidad en la definición …
=> fix : nombre del permiso

omni/pro/import_export.py
Este PR aborda los ajustes necesarios para mejorar el funcionamiento de QueryExport en PostgreSQL.
- Ajuste en la lógica de construcción de diccionarios anidados.
- Mejora en la gestión de relaciones uno-a-muchos y muchos-a-muchos.
- Corrección de errores en la comparación y fusión de diccionarios.
Estos cambios son necesarios para garantizar que la exportación de datos desde PostgreSQL maneje correctamente las relaciones complejas y evite la duplicación de datos.
- Pruebas de integración para asegurar la correcta exportación de datos con relaciones complejas.
Se recomienda revisar los cambios en la lógica de fusión de diccionarios para asegurar que no se introduzcan inconsistencias en los datos exportados.
[NVOMS-3214]: https://omnipro.atlassian.net/browse/NVOMS-3214?atlOrigin=eyJpIjoiNWR …
=> Nvoms 3214 0 pre requisitos ajustar el funcionamiento de query export postgre sql
