Omnipro-Solutions/saas-ms-library

- omni/pro/protos/grpc_connector.py
- omni/pro/protos/util.py
- setup.py
> feat: Add format request function

- omni/pro/protos/grpc_connector.py
update order of code and pass kwargs and args to call_rpc_fuction
> refactor: update Omnichannel

- omni/pro/database.py
add function to use on all ms to register conection to existent tenant on redis
> feature: add register connection on database

- omni/pro/database.py
- omni/pro/redis.py
- solve redis import to ms_register_connection get redis connection
- add  condition to prevent get data conection on local develop from cloud map
> fix: import errors

- omni/pro/database.py
- omni/pro/database_connection.py
- move function to other modulo to prenvent circular import
- fix por value on redis
> fix: circular import

- omni/pro/redis.py
> fix: port value

- omni/pro/config.py
- omni/pro/database.py
- requirements.txt
- add library fakeredis json
- add condition to get fakeredis when flag TESTING is True
> feat: add fakeredis to testing

- omni/pro/database.py
- add singleton class to generate only one server to fakeredis
> refactor: add singleton to fakeserver

- omni/pro/models/base.py
- setup.py
- update setup tu find requirements
- refactor base definition to sqlachemy
> refactor: update setup and base model

- omni/pro/models/base.py
- add to base implements def get_or_sync
- remove unused code
> feat: add new method def get_or_sync

- omni/pro/database.py
- omni/pro/models/base.py
> refactor(Library): 🐍 Refactor Library Peewee deprecate

- omni/pro/exceptions.py
- add exception to manage not found registers
> feat: add exception to not found

- omni/pro/database.py
- omni/pro/decorators.py
adding 'pg_db_params' in context
> refactor: replacing '__' to '.' in query filter

- omni/pro/database.py
- omni/pro/models/base.py
1. Add create, update, delete in  Base Model SQL Alchemy
> refactor(Library): 🐍 Refactor Library

- omni/pro/grpc_interceptor.py
1. Add Class LoggingInterceptor for reuse in the diferents ms
> feat(Library): 🐍 Add interceptor class log access service grpc

- omni/pro/exceptions.py
- omni/pro/util.py
- add functions add_or_remove_document_relations, remove_document_relations and add_document_relations on util
- add new exception AlreadyExistError
> feat: add new exception and funtions on utils

- omni/pro/database.py
- omni/pro/protos/grpc_connector.py
se cambio la forma de obtener el host y port de cloudmap, ahora se obtienen de redis
> refactor omnichannel

- omni/pro/util.py
ahora se puede enviar un dict en el get_or_sync para un modelo
> changes in the functions of relations_documents

- omni/pro/aws.py
- omni/pro/database.py
- omni/pro/decorators.py
- omni/pro/util.py
- update aws to allow donwload s3 files
- update class name to AWSS3Client
- add get_aws_s3_config funtion on database to get settings of s3
- add decorator to set s3 on context
> feat: add s3

- omni/pro/protos/grpc_connector.py
- Added a check to see if the response has a `response_standard` attribute.
- Set `success` to True if the status code of `response_standard` is in the range 200-300.
> Add status code validation in grpc_connector.py

- omni/pro/redis.py
> Refactor RedisManager instantiation in

- omni/pro/files.py
- omni/pro/import_export.py
The commit refactors the DocumentStrategy class to include an abstract method for adding data to files. Additionally, the CSVDocumentStrategy class now implements the add_data method to append data to CSV files. This change enhances the flexibility and usability of the DocumentStrategy API, enabling users to easily add data to different types of documents. No significant consequences or issues to note.
Related to #123
> Refactor and extend DocumentStrategy and CSVDocumentStrategy classes

- omni/pro/descriptor.py
- omni/pro/files.py
- omni/pro/import_export.py
- omni/pro/protos/grpc_connector.py
improve data handling
- Implement a try-except block to catch RecursionError when describing
recursive Mongo models, preventing application crashes and logging the
error for further investigation.
- Introduce NaN replacement with None in CSV and JSON data handling to
ensure cleaner and more consistent data ingestion.
- Enhance QueryExport functionality by enabling data fetching within a
specified date range, offering more targeted data retrieval
capabilities.
- Refactor gRPC connector's channel options handling, including default
override options and increasing message length limits, improving
robustness and flexibility of gRPC communications.
- Minor code refactoring for readability and maintainability across
various modules.
Related issues: #12345 (data handling improvements), #67890 …
> Handle recursive model description failure and

- omni/pro/register.py
- omni/pro/stack.py
- omni/pro/topology.py
Changes in topology , used importlib
> Refactor import in stack and register

- omni/pro/database.py
Updated MongoDB connection string to use credentials, enforcing authentication and enabling SSL encryption. This change improves database security by securely transmitting credentials and encrypting traffic between the application and the database. An authentication source is also explicitly specified to manage user credentials effectively.
Resolves #123 for database security enhancements.
> Enhance MongoDB security and connection

- omni/pro/database.py
The MongoConnection class initialization now supports dynamic URI query parameters enabling versatile database connections. This change moves away from hardcoded authentication source and SSL options, thereby allowing for additional configuration determined by the 'complement' dictionary passed to the constructor. This update enhances the adaptability of the database connection process to various MongoDB deployment scenarios.
> Enhanced MongoDB connection flexibility

- omni/pro/descriptor.py
- omni/pro/models/base.py
add validation for is_filterable,is_exportable,is_importable in descriptor.py
add param in context and audit in base.py
> Update descriptor.py and base.py

- omni/pro/database_connection.py
Connection evaluation logic in database connection setup is updated to disregard the 'complement' field during debug mode or when it's absent. This prevents potential issues with incomplete connection configurations and aligns with the logic designed for debug scenarios.
The associated benefit of this change is in avoiding unnecessary processing for an optional field when it's either not relevant (in debug) or not provided, ensuring smoother setup of database connections.
#Refactoring #DatabaseConnectionManagement
> Optimize connection eval for missing complement

- omni/pro/check_migration.py
- requirements.txt
- setup.py
Se ha mejorado el proceso de validación durante las migraciones de la base de datos y se ha añadido la funcionalidad para verificar la existencia de la base de datos y crearla si es necesario. Ahora se manejan mejor las excepciones y se agregan mensajes informativos más claros durante la ejecución.
Se han actualizado las dependencias en `setup.py` y `requirements.txt` para incluir `sqlalchemy-utils` y `alembic` con versiones específicas requeridas para nuevas funcionalidades.
Refs #develop
> feat(omni/pro): mejora en proceso de validación y manejo de DB

- omni/pro/database/postgres.py
Refactored the `retrieve_record` method in `postgres.py` to allow for more sophisticated filtering with both AND and OR conditions. This update introduces the ability to pass in a list of filter groups to handle OR conditions, as well as nested dictionaries for complex AND/OR logic, thus enhancing the flexibility of record retrieval without affecting existing dictionary-based implementations.
> feat(postgres): enhance `retrieve_record` to support complex filters

- omni/pro/database/postgres.py
Restructure the retrieval functions in the Postgres module to support complex AND/OR query conditions. The `_retrieve_records` method now constructs a SQLAlchemy query object, allowing for nested AND/OR conditions. Updated the `retrieve_record` and `retrieve_records` methods to utilize the new `_retrieve_records` method, maintaining backward compatibility with dictionary-based filters while enabling more advanced query construction.
Example usage has been updated to reflect the enhanced filtering capabilities.
BREAKING CHANGE: The `retrieve_record` method signature has changed. Filters must now be passed as a dictionary for AND conditions or a list for OR conditions. Nested OR condition handling is not yet implemented and will raise a NotImplementedError.
> refactor(postgres): improve retrieval logic with AND/OR conditions

- omni/pro/mirror_model.py
> Refactor MirrorModelServiceMongo class in mirror_model.py

- omni/pro/airflow/actions.py
union modified_fields and instance._changed_fields
> Refactor send_to_airflow

- omni/pro/database/postgres.py
The code changes in `postgres.py` refactor the `PostgresDatabaseManager` class to handle date formatting. Specifically, the changes include adding support for parsing and formatting datetime values in the database queries. This aligns with the recent user commits and repository commits, which focus on improving the codebase and adding new features.
> Refactor PostgresDatabaseManager to handle date formatting

- omni/pro/decorators.py
- requirements.txt
- setup.py
The code changes in `requirements.txt` and `setup.py` update the `newrelic` dependency to version 9.10.0. This aligns with recent user commits and repository commits, which focus on improving the codebase and adding new features.
Add wraps to resources_decorator for function_trace
> chore: Update newrelic dependency to version 9.10.0

- omni/pro/import_export.py
The code changes in `import_export.py` refactor the `QueryExport` class in the `ImportExportBase` module. The changes optimize the generation of the SQL query by using SQLAlchemy's inspector to retrieve foreign keys and related fields. This improves the efficiency and readability of the code. The recent user commits and repository commits indicate a focus on refactoring and improving the codebase.
> Refactor ImportExportBase to optimize SQL query generation

- omni/pro/import_export.py
https://omnipro.atlassian.net/browse/NVOMS-2481
Se mejora los nombres para los datos de la Query, evitando palabras reservadas de SQL. Ejemplo
`order` palabra reservada de SQL , pero es un nombre de una tabla
- Se crea una variable con el alias y se agrega `AS` en la query
Al exportar datos del modelo `order` había un error de sintaxis en la query, revisando re encuentra que `order` es una palabra reservada por lo tanto no podíamos usarla y por ende el error de sintaxis 
- Se probó  la query nativamente en pgAdmin
- Se realizado el flujo completo de exportación 
@julianvaldes24 Actualizar librería en el servicio de `sale`
> Refactor import_export.py to use table aliases in SQL query

- omni/pro/models/base.py
- [NVOMS-2621 - Add locale field to ContextSchema](https://github.com/Omnipro-Solutions/saas-ms-library/pull/833)
- [] Bug fix (cambios que solucionan un problema)
> Merge Develop to Master

- omni/pro/database/postgres.py
- omni/pro/models/base.py
- omni/pro/stack.py
- omni/pro/webhook/webhook_handler.py
Almacena los objectos a los que se les ha hecho CRUD dentro de una sesion o stack
Utilizar estos atributos para enviarlos en un nuevo hilo a los webhook
Postman
<Incluir imágenes o enlaces a capturas de pantalla que demuestren los cambios realizados>
- [* ] Nueva característica (cambios que añaden funcionalidad)
- [ *] Mejoras de rendimiento
- [* ] Mi código sigue las directrices de estilo de este proyecto
- [* ] He realizado una auto-revisión de mi propio código
- [* ] He comentado mi código, especialmente en áreas difíciles de entender
- [* ] He añadido pruebas que demuestran que mi arreglo es efectivo o que mi característica funciona
- [* ] Los cambios necesarios han sido confirmados como efectivos y deseados en pruebas
<Información adicional o notas que los revisores deben tener en …
> Feat nvoms 2768

- omni/pro/mirror_model.py
Este PR agrega las nuevas funciones en mirror_model, tanto en las bases de datos SQL como NO_SQL.
- Añadido las funciones para hacer las operaciones en lotes con bulk, tanto en mongo como en sql
Estos cambios son necesarios para la mejora de airflow.
-  Se realizaron pruebas ejecutando el cliente y llamando los métodos.
N/A
N/A
> NVOMS-2765 - Mejoras Airflow 5.3 WebHook de tipo Internal

- omni/pro/descriptor.py
- omni/pro/mirror_model.py
- [NVOMS-2765 - Mejoras Airflow 5.3 WebHook de tipo Internal](https://github.com/Omnipro-Solutions/saas-ms-library/pull/844)
N/A
[NVOMS-2765]: https://omnipro.atlassian.net/browse/NVOMS-2765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Merge Develop in Master

- omni/pro/template/loader.py
He añadido una nueva función para renderizar plantillas utilizando la librería Jinja2. Esta funcionalidad permite a los microservicios importar y utilizar una función para renderizar plantillas con data proporcionada.
1. **Nuevo archivo**: `omni/pro/template/__init__.py`
- Se ha creado un nuevo archivo `__init__.py` para inicializar el módulo `template`.
2. **Nuevo archivo**: `omni/pro/template/loader.py`
- Se ha añadido el archivo `loader.py`, que contiene la función `render_to_string`.
Estos cambios se realizaron para facilitar la renderización de plantillas en los microservicios. Al centralizar la lógica de renderización en una función importable, se mejora la mantenibilidad y la consistencia del código.
1. **Instalación de dependencias**: Asegúrate de tener instalada la librería …
> feat: Add render_to_string function for Jinja2 template rendering

- omni/pro/decorators.py
https://omnipro.atlassian.net/browse/NVOMS-2524
Este PR refactoriza la función `resources_decorator` para añadir una validación de permisos a través del método `permission_required`. Los cambios incluyen la verificación de permisos antes de ejecutar la función decorada, utilizando un cliente gRPC para validar los permisos del usuario en cuestión.
- **Refactorización de `resources_decorator`**:
- Se añadió la validación de permisos dentro del `resources_decorator`. Si el usuario no tiene los permisos requeridos, la función decorada no se ejecutará y se devolverá una respuesta de error.
- El parámetro `permission_code` fue añadido al decorador para definir el código de permiso necesario.
- **Implementación de `permission_required`**:
- Esta nueva función realiza una llamada RPC al servicio …
> Nvoms 2524 1 refactor microservice user para que use capa de operaciones models operations service

- omni/pro/decorators.py
TK - 2524 Permisos 
https://omnipro.atlassian.net/browse/NVOMS-2524
> Refactor resource decorator and permission handling

- omni/pro/models/base.py
- omni/pro/webhook/webhook_handler.py
Info a debug logger
- Mejor seguimiento
N/A
N/A
- [] Nueva característica (cambios que añaden funcionalidad)
N/A
> feat: Change logger info by debug

- omni/pro/celery/celery_redis.py
- omni/pro/webhook/webhook_handler.py
Se le añade metodo que devuelve la cola con menos tareas
- Eficiencia
Postman
N/A
- [*] Mejoras de rendimiento
N/A
> Feat nvoms 2982

- omni/pro/models/base.py
- omni/pro/user/access.py
En este pull request he realizado varias modificaciones para mejorar y extender la funcionalidad de los campos de auditoría en nuestra aplicación. Estos cambios se centran en la refactorización de ciertos aspectos del código para hacerlos más robustos y escalables.
He reestructurado el orden de las importaciones en el archivo `base.py` para mejorar la organización del código y he introducido el uso de `INTERNAL_USER` para el contexto de usuario, asegurando así una mejor gestión de auditorías cuando no se proporciona un usuario explícito. Además, he añadido un nuevo método `dt_to_ts` en la clase `Base`, que convierte objetos `datetime` a objetos `Timestamp`, lo que facilita la gestión de timestamps a lo largo del proyecto.
Estos cambios son parte de una iniciativa para estandarizar y …
> Refactor code to improve readability and maintainability

- omni/pro/models/base.py
https://omnipro.atlassian.net/browse/NVOMS-3045
Se agrego la propiedad `click_house` en las Bases de las clases, por defecto en True, si se requiere en False, se actualiza directamente en la subclase
Se requiere que las clases tengan esta propiedad
> Add click_house attribute to BaseDocument and Base classes

- omni/pro/webhook/webhook_handler.py
Se crea tarea para enviar los records actualizado o creados a click house
- Se crea tarea de celery para enviar a click house
N/A
N/A
> feat: create task to click house

- omni/pro/decorators.py
Se utiliza el proto de respuesta del servicio correspondiente
> Update resources_decorator to handle message_response correctly 

- omni/pro/mirror_model.py
Este PR refactoriza la función _convert_fields_to_db_types del MirrorModelSQL.
- Se implementó la lógica para manejar correctamente las llaves foráneas asociadas a columnas de tipo INTEGER.
- Se añadió un mapa foreign_key_map para mapear modelos relacionados y sus campos asociados.
- Se optimizó el proceso para convertir valores de campos INTEGER y resolver relaciones de claves foráneas usando el pg_manager.
- Se corrigió la validación y asignación de valores relacionados con modelos externos, asegurando que los datos sean consistentes con la base de datos.
- Este cambio asegura que los modelos réplicas manejen correctamente los valores de sus claves foráneas, especialmente al interactuar con datos provenientes de bases de datos MongoDB y SQL.
- Resuelve errores al procesar registros que …
> NVOMS-3088 - Replicas de Sale

- omni/pro/celery/call_sync_mirror_model.py
- omni/pro/import_export.py
- omni/pro/mirror_model.py
Se agrego SynchronizedMirrorModel, para llamar agregar la tarea en celery, se ajustó el import y se agrego logica para el mirror model
Se agrego SynchronizeMirrorModel  para encolar las tareas en celey, se ajustó el import para mongo, ya que el nombre de la collection se estaba pasando mal, se ajustó el import para sql ya que al hacer ciertas consultas funcionaba bien, consultas para llamar un campo de una relación, se agregó la bandera delete en mirror_model para saber que se debe compara los ids que llegan, contra los ids que estan en la réplica y eliminar los agregados de mas 
- Se probo en modelos como: Quants, User, DeliveryMethod, Warehouse
> Implement synchronized mirror model and enhance multi-update func

- omni/pro/models/base.py
Se modifico la lógica de la def to_proto para incluir el exclude, que permite eliminar campos del message al que se esta pasando
también se agregó en las bases __exclude_fields__ 
- Add __exclude_fields__ 
- Modificación al to_proto de las Bases
Se modifico el to_proto para eliminar campos que al momento de llamar a un modelo y este tenga otro modelo relacionado, se puede eliminar algunos campos para el modelo anidado 
<Descripción de las pruebas que se han realizado para verificar los cambios>
- Pruebas con Sales,Order , State, Flow, Channel
- Pruebas con Rules, DeliveryMethod, DeliveryLocality, DeliveryWarehouses,ScheduleWork
> Protos anidados devuelven una cantidad mínima de campos

- omni/pro/webhook/webhook_handler.py
Webhook de tipo click house, se enviar order_ids relacionadas.
.
N/A
N/A
> feat: order_ids to task storage

- omni/pro/database/postgres.py
NVOMS-3183 - Optimización de consultas utilizando el parámetro fields en microservicios con base de datos SQL
Referencia (https://omnipro.atlassian.net/browse/NVOMS-3183)
Descripción
Este cambio optimiza las consultas a la base de datos utilizando el parámetro fields en los microservicios que interactúan con una base de datos SQL. El objetivo principal es mejorar el rendimiento de las consultas al permitir la selección de campos específicos tanto de modelos principales como de modelos relacionados.
¿Cómo funciona?
Cuando se realiza una consulta, ahora es posible especificar qué campos devolver de modelos relacionados, lo que reduce la cantidad de datos que se procesan y se devuelven. Por ejemplo, cuando se consulta el modelo order_line, en el parámetro fields se puede incluir algo como …
> feat: transform_objects_by_fields

- omni/pro/aws/s3.py
He realizado mejoras en la clase `AWSS3Client` para añadir la funcionalidad de subir un archivo a un bucket de S3. Estas mejoras facilitan la integración con AWS S3 al permitir la carga sencilla de archivos con el método `put_object`.
- **Nuevo método `put_object` en la clase `AWSS3Client`:**  
He añadido el método `put_object` que permite subir archivos a un bucket de S3. Este método toma como parámetros el contenido del archivo (`body`), la clave del objeto en S3 (`key`), y un control de acceso opcional (`ACL`) que por defecto es privado. También admite otros argumentos opcionales a través de `**kwargs`.
La motivación detrás de este cambio es facilitar la gestión de archivos en S3 dentro de nuestra aplicación. Al proporcionar un método específico para subir archivos, mejoramos la …
> feat: add put_object method to upload files to S3 bucket

- omni/pro/import_export.py
Este PR implementa la clase `QueryExport` que permite consultar datos de bases de datos SQL  de manera dinámica. Además, agrega la clase `DynamicQueryPostgresService` para manejar consultas SQL complejas con campos anidados y relaciones entre modelos.
- Se añadió la clase `QueryExport` para manejar consultas a bases de datos SQL.
- Se integró `DynamicQueryPostgresService` para generar consultas SQL dinámicas con soporte para campos anidados.
- Se implementó un mecanismo de validación para asegurarse de que los campos de relación se usen correctamente en las consultas SQL.
- Se agregó soporte para consultas de relaciones muchos-a-muchos (M2M) en la generación de consultas SQL.
- Se mejoró el manejo de fechas y validación de formato para las consultas.
Este cambio es necesario para permitir …
> feat : DynamicQueryPostgresService

- omni/pro/aws/s3.py
En este pull request, he introducido cambios significativos en el módulo `s3.py` de nuestra aplicación para mejorar la interacción con el servicio AWS S3. Estos cambios incluyen la importación del paquete `boto3`, la implementación de métodos adicionales para operaciones básicas de S3 y la restructuración de la configuración inicial del cliente S3.
1. **Importación de `boto3`:** 
- Se añadió la línea `import boto3` al inicio del archivo para permitir el uso del SDK de AWS, necesario para las interacciones con recursos de S3.
2. **Cambio en la configuración del cliente S3:**
- La configuración del cliente S3 ahora se almacena en `self.config` y se asigna a `kwargs["config"]` para permitir su reutilización.
3. **Nuevo método `get_resource`:** 
- Implementé un método llamado `get_resource` …
> feat: add get_resource and get_object methods to AWSS3Client for enhanced S3 interactions

- omni/pro/aws/s3.py
- omni/pro/files.py
Se refactorizo el FileProcessor y las clases de las estrategias para exportar datos, para CSV se realizó un escalado vertical 
- Pruebas manuales del flujo
> Implement upload_fileobj method in AWSS3Client and refactor document strategies for CSV and JSON handling

- omni/pro/descriptor.py
Se agrego el code en el campo relation de los fields de tipo relationship
Frond requiere el code en el relation para los fields de tipo relationship
<Descripción de las pruebas que se han realizado para verificar los cambios>
- Se ejecuto el proceso de register_model
> Add code field to relation property in Descriptor class

- omni/pro/database/mongo.py
- omni/pro/database/postgres.py
Este PR reduce la dependencia de gRPC en las operaciones de los microservicios, promoviendo una arquitectura más desacoplada y flexible.
- Refactorización de los servicios para desacoplar las llamadas gRPC.
- Disminuir el acoplamiento con gRPC permite una mayor flexibilidad en la arquitectura.
- Mejora la interoperabilidad con otros servicios y sistemas.
- Facilita la escalabilidad y mantenibilidad de los microservicios.
- Se ejecutaron las cruds para verificar el comportamiento.
N/A
N/A
> NVOMS-3103 - mejora en las operations de los microservicios

- omni/pro/descriptor.py
- omni/pro/models/base.py
En esta actualización, realicé modificaciones en el archivo `descriptor.py` de la aplicación para mejorar la generación de descriptores de modelos y relaciones. Los cambios se centran en simplificar y unificar cómo se define el código y proporcionar información adicional acerca de las relaciones.
1. **Modificación en la definición de código de modelo:**
- Anteriormente, el código del modelo se obtenía a través de `model._meta.get("collection")` si estaba disponible, caso contrario, se usaba el nombre del modelo en minúsculas.
- Ahora, simplemente se usa el nombre del modelo en minúsculas (`model.__name__.lower()`).
2. **Añadido de campos primitivos en relaciones:**
- En la definición de relaciones, se añadió un nuevo campo `primitive_field`, que contiene una lista separada por comas de …
> feat: update Descriptor class to refine model code retrieval and enhance relationship property details
